import streamlit as st
import pandas as pd
import sqlite3
from datetime import datetime
from fpdf import FPDF
import io

# 1. KONFIGURASI HALAMAN
st.set_page_config(page_title="FIN-Saku: Kendali Modal UMKM", layout="wide")

# --- DATABASE ENGINE ---
conn = sqlite3.connect('finsaku_pro_final.db', check_same_thread=False)
c = conn.cursor()
c.execute('''CREATE TABLE IF NOT EXISTS transaksi
             (id INTEGER PRIMARY KEY, tanggal TEXT, bulan TEXT, minggu TEXT, 
              omzet REAL, laba REAL, prive REAL, periode TEXT)''')
conn.commit()

# --- FUNGSI TOOLS ---
def format_rp(angka):
    try:
        abs_angka = abs(float(angka))
        formatted = "{:,.0f}".format(abs_angka).replace(",", ".")
        if angka < 0: return f"Rp -{formatted}"
        return f"Rp {formatted}"
    except: return "Rp 0"

def clean_to_int(teks):
    if not teks: return 0
    return int("".join(filter(str.isdigit, str(teks))))

# --- FUNGSI GENERATE PDF ---
def generate_pdf(nama_usaha, periode, omzet, laba, prive, m_awal, m_akhir):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(190, 10, f"LAPORAN KEUANGAN: {nama_usaha.upper()}", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(190, 10, f"Periode: {periode}", ln=True, align='C')
    pdf.ln(10)
    pdf.line(10, 35, 200, 35)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, "Keterangan Akuntansi", border=1); pdf.cell(90, 10, "Nilai (IDR)", border=1, ln=True, align='C')
    
    pdf.set_font("Arial", '', 12)
    data_list = [
        ("Total Pendapatan (Omzet)", format_rp(omzet)),
        ("Laba/Rugi Bersih", format_rp(laba)),
        ("Prive (Penarikan Modal)", format_rp(prive)),
        ("Modal Awal Periode", format_rp(m_awal)),
        ("Kas/Modal Akhir", format_rp(m_akhir))
    ]
    for k, v in data_list:
        pdf.cell(100, 10, k, border=1); pdf.cell(90, 10, v, border=1, ln=True, align='R')
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(190, 10, f"Generated by FIN-Saku on {datetime.now().strftime('%Y-%m-%d')}", align='R')
    return pdf.output(dest='S').encode('latin-1')

# 2. UI CUSTOM
st.markdown("""
<style>
    .stApp { background-color: #001f3f !important; }
    .stApp, .stApp p, .stApp label, .stApp h1, .stApp h2, .stApp h3 { color: #ffffff !important; }
    .white-card {
        background-color: #ffffff !important; padding: 20px; border-radius: 12px; 
        border-left: 8px solid #FFD700; margin-bottom: 15px; color: #000000 !important;
    }
    .white-card * { color: #000000 !important; }
    .stButton>button { background-color: #FFD700 !important; color: #000 !important; font-weight: bold; }
    section[data-testid="stSidebar"] { background-color: #00152b !important; border-right: 1px solid #FFD700; }
</style>
""", unsafe_allow_html=True)

# --- LOGIKA DATA ---
df = pd.read_sql_query("SELECT * FROM transaksi", conn)

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='text-align:center; color:#FFD700;'>💰 FIN-Saku</h1>", unsafe_allow_html=True)
    nama_u = st.text_input("Nama Usaha", "UMKM Maju Bersama")
    sektor = st.selectbox("Sektor Usaha:", ["Kuliner", "Retail", "Jasa", "Produksi"])
    modal_awal = clean_to_int(st.text_input("Uang Kas Awal (Modal)", "7000000"))
    
    total_laba_all = df['laba'].sum() if not df.empty else 0
    total_prive_all = df['prive'].sum() if not df.empty else 0
    modal_skrg_all = modal_awal + total_laba_all - total_prive_all
    
    st.markdown(f"Modal Awal: **{format_rp(modal_awal)}**")
    st.markdown(f"<h3 style='color:#FFD700;'>Kas Saat Ini:<br>{format_rp(modal_skrg_all)}</h3>", unsafe_allow_html=True)
    st.write("---")
    hpp_val = clean_to_int(st.text_input("HPP Produk", "5000"))
    hrg_val = clean_to_int(st.text_input("Harga Jual", "15000"))
    prive_pct = st.slider("Jatah Prive (%)", 0, 100, 30)

# --- INPUT TRANSAKSI ---
st.title(f"Dashboard: {nama_u}")
rekap_mode = st.radio("Pilih Periode Catat:", ["Harian", "Mingguan", "Bulanan"], horizontal=True)

col_in, col_info = st.columns([1, 1.2])

with col_in:
    now = datetime.now()
    if rekap_mode == "Harian":
        tgl_i = st.date_input("Tanggal", now)
        v_tgl, v_bln = tgl_i.strftime("%Y-%m-%d"), tgl_i.strftime("%B %Y")
        v_mng = f"Minggu ke-{((tgl_i.day - 1) // 7 + 1)}"
    elif rekap_mode == "Mingguan":
        tgl_i = st.date_input("Tanggal Referensi", now)
        v_bln = tgl_i.strftime("%B %Y")
        v_mng = f"Minggu ke-{((tgl_i.day - 1) // 7 + 1)}"
        v_tgl = f"Rekap {v_mng} - {v_bln}"
    else:
        v_bln = st.selectbox("Pilih Bulan", ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"])
        v_bln = f"{v_bln} {now.year}"
        v_tgl, v_mng = f"Rekap Bulanan {v_bln}", "-"

    omzet_in = st.number_input("Total Omzet Penjualan", value=0, step=10000)
    laba_in = omzet_in - (omzet_in * (hpp_val / hrg_val) if hrg_val > 0 else 0)
    prive_in = laba_in * (prive_pct / 100) if laba_in > 0 else 0

    if st.button("🔔 SIMPAN TRANSAKSI"):
        if omzet_in > 0:
            c.execute("INSERT INTO transaksi (tanggal, bulan, minggu, omzet, laba, prive, periode) VALUES (?, ?, ?, ?, ?, ?, ?)",
                      (v_tgl, v_bln, v_mng, omzet_in, laba_in, prive_in, rekap_mode))
            conn.commit()
            st.success("Data Tersimpan!")
            st.rerun()

with col_info:
    st.markdown(f"""<div class="white-card">
        <h3>📢 Status</h3><p><b>{v_mng}</b> | <b>{v_bln}</b></p>
        <hr><p>Laba Estimasi: <b>{format_rp(laba_in)}</b><br>Prive: <b>{format_rp(prive_in)}</b></p>
    </div>""", unsafe_allow_html=True)

# --- LAPORAN & KUR ---
if not df.empty:
    st.write("---")
    tab_rep, tab_kur, tab_rev = st.tabs(["📊 LAPORAN KEUANGAN", "🏦 ANALISIS KUR BRI", "🛠️ REVISI"])
    
    with tab_rep:
        list_b = df['bulan'].unique().tolist()
        sel_b = st.selectbox("Pilih Bulan Laporan:", list_b, index=len(list_b)-1)
        
        db_b = df[df['bulan'] == sel_b]
        o_b, l_b, p_b = db_b['omzet'].sum(), db_b['laba'].sum(), db_b['prive'].sum()
        
        idx = list_b.index(sel_b)
        lalu = df[df['bulan'].isin(list_b[:idx])]
        m_awal_b = modal_awal + lalu['laba'].sum() - lalu['prive'].sum()
        m_akhir_b = m_awal_b + l_b - p_b

        col1, col2 = st.columns(2)
        with col1:
            st.markdown(f"""<div class="white-card"><h3 style="text-align:center;">LABA RUGI</h3><hr>
                <table style="width:100%;">
                    <tr><td>Total Omzet</td><td style="text-align:right;">{format_rp(o_b)}</td></tr>
                    <tr style="color:red;"><td>Beban HPP</td><td style="text-align:right;">({format_rp(o_b - l_b)})</td></tr>
                    <tr style="font-weight:bold; border-top:2px solid black;"><td>LABA BERSIH</td><td style="text-align:right;">{format_rp(l_b)}</td></tr>
                </table></div>""", unsafe_allow_html=True)
        with col2:
            st.markdown(f"""<div class="white-card"><h3 style="text-align:center;">PERUBAHAN MODAL</h3><hr>
                <table style="width:100%;">
                    <tr><td>Modal Awal</td><td style="text-align:right;">{format_rp(m_awal_b)}</td></tr>
                    <tr><td>Laba Bersih</td><td style="text-align:right;">{format_rp(l_b)}</td></tr>
                    <tr style="color:red;"><td>Prive</td><td style="text-align:right;">({format_rp(p_b)})</td></tr>
                    <tr style="font-weight:bold; border-top:2px solid black; background:#FFD700;"><td>KAS AKHIR</td><td style="text-align:right;">{format_rp(m_akhir_b)}</td></tr>
                </table></div>""", unsafe_allow_html=True)
        
        pdf_f = generate_pdf(nama_u, sel_b, o_b, l_b, p_b, m_awal_b, m_akhir_b)
        st.download_button("📥 DOWNLOAD PDF", data=pdf_f, file_name=f"Laporan_{sel_b}.pdf")

    with tab_kur:
        st.subheader("🏦 Konsultasi Strategis KUR")
        if df['bulan'].nunique() < 3:
            st.error(f"🚩 BELUM LAYAK: Butuh {3-df['bulan'].nunique()} bulan data lagi.")
        elif l_b <= 0:
            st.error("🚩 DITOLAK: Usaha bulan ini rugi. Bank hanya membiayai usaha laba.")
        else:
            st.success("✅ STATUS: LAYAK AJUKAN")
            tenor = st.select_slider("Tenor (Bulan):", options=[12, 24, 36])
            plafon = l_b * 12 # Contoh logika plafon
            cicilan = (plafon/tenor) + (plafon*0.005)
            st.markdown(f'<div class="white-card">Plafon Rekomendasi: <b>{format_rp(plafon)}</b><br>Estimasi Cicilan: <b>{format_rp(cicilan)}/bln</b></div>', unsafe_allow_html=True)

    with tab_rev:
        target = st.selectbox("Pilih data dihapus:", [f"{r['id']} | {r['tanggal']}" for _, r in df.iterrows()])
        if st.button("🗑️ HAPUS"):
            c.execute(f"DELETE FROM transaksi WHERE id={target.split(' | ')[0]}")
            conn.commit()
            st.rerun()
else:
    st.info("Mulai catat transaksi pertama Anda!")
